# Generated by Django 3.2.23 on 2023-12-11 20:22

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eprints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('published_time', models.DateTimeField()),
                ('source', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('is_positive', models.BooleanField()),
                ('is_latest', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URLs', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('published_time', models.DateTimeField()),
                ('source', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('is_positive', models.BooleanField()),
                ('is_latest', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='youtube_csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='csv_files/')),
                ('published_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='youtube_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=700, null=True)),
                ('views', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=900, null=True)),
                ('link', models.CharField(blank=True, max_length=800, null=True)),
                ('published_time_ago', models.CharField(blank=True, max_length=200, null=True)),
                ('duration_of_video', models.CharField(blank=True, max_length=200, null=True)),
                ('channel_name', models.CharField(blank=True, max_length=500, null=True)),
                ('type_of_platform', models.CharField(blank=True, max_length=200, null=True)),
                ('sentiment_analysis', jsonfield.fields.JSONField(blank=True, null=True)),
                ('summary_json', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
    ]
