# Generated by Django 3.2.23 on 2023-12-11 20:27

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_cluster_head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('is_latest', models.BooleanField()),
                ('sentiment_report', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='news_obj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_clustered', models.BooleanField(default=False)),
                ('source_type', models.CharField(choices=[('website', 'website'), ('youtube', 'youtube'), ('others', 'others')], max_length=200)),
                ('source_name', models.CharField(blank=True, max_length=200, null=True)),
                ('source_url', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=800, null=True)),
                ('published_time', models.DateTimeField(blank=True, null=True)),
                ('is_positive', models.BooleanField(default=False)),
                ('is_latest', models.BooleanField(default=False)),
                ('views', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=900, null=True)),
                ('published_time_ago', models.CharField(blank=True, max_length=200, null=True)),
                ('duration_of_video', models.CharField(blank=True, max_length=200, null=True)),
                ('channel_name', models.CharField(blank=True, max_length=500, null=True)),
                ('type_of_platform', models.CharField(blank=True, max_length=200, null=True)),
                ('sentiment_analysis', jsonfield.fields.JSONField(blank=True, null=True)),
                ('summary_json', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='URL',
        ),
        migrations.DeleteModel(
            name='youtube',
        ),
        migrations.DeleteModel(
            name='youtube_csv',
        ),
        migrations.DeleteModel(
            name='youtube_data',
        ),
        migrations.AddField(
            model_name='news_cluster_head',
            name='cluster_obj',
            field=models.ManyToManyField(to='api.news_obj'),
        ),
    ]
