# Generated by Django 4.2.5 on 2023-12-15 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20231212_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_cluster_head',
            name='cluster_obj',
        ),
        migrations.RemoveField(
            model_name='news_cluster_head',
            name='is_latest',
        ),
        migrations.RemoveField(
            model_name='news_cluster_head',
            name='sentiment_report',
        ),
        migrations.RemoveField(
            model_name='news_cluster_head',
            name='source',
        ),
        migrations.AddField(
            model_name='news_cluster_head',
            name='NEGATIVE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news_cluster_head',
            name='NEUTRAL',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news_cluster_head',
            name='POSITIVE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news_cluster_head',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 18, 41, 59, 639460)),
        ),
        migrations.AddField(
            model_name='news_cluster_head',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news_cluster_head',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news_cluster_head',
            name='main_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news_cluster_head',
            name='negative_sentence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news_cluster_head',
            name='neutral_sentence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news_cluster_head',
            name='positive_sentence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news_cluster_head',
            name='published_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news_cluster_head',
            name='published_time_ago',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news_cluster_head',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news_cluster_head',
            name='sentiment_analysis_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news_cluster_head',
            name='summary_article',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news_cluster_head',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news_cluster_head',
            name='website_data_cluster_obj',
            field=models.ManyToManyField(related_name='website_data_cluster_obj', to='api.news_obj'),
        ),
        migrations.AddField(
            model_name='news_cluster_head',
            name='youtube_data_cluster_obj',
            field=models.ManyToManyField(related_name='youtube_data_cluster_obj', to='api.news_obj'),
        ),
        migrations.AddField(
            model_name='news_obj',
            name='clustered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news_obj',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 18, 41, 59, 641460)),
        ),
        migrations.AddField(
            model_name='news_obj',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news_obj',
            name='is_cluster_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news_obj',
            name='main_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news_obj',
            name='negative_sentence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news_obj',
            name='neutral_sentence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news_obj',
            name='positive_sentence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news_obj',
            name='published_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='news_obj',
            name='summary_article',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news_obj',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news_cluster_head',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news_cluster_head',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news_cluster_head',
            name='title',
            field=models.CharField(default='Your Default Title', max_length=800),
        ),
        migrations.AlterField(
            model_name='news_obj',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news_obj',
            name='published_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='news_obj',
            name='source_type',
            field=models.CharField(choices=[('website', 'website'), ('youtube', 'youtube'), ('eprints', 'eprints'), ('others', 'others')], max_length=200),
        ),
        migrations.AlterField(
            model_name='news_obj',
            name='title',
            field=models.CharField(default='Your Default Title', max_length=800),
        ),
    ]
